Add Nginx Unit plugin to documentation
certbot/certbot pull request #10110
Opened 2024-12-29 15:48 UTC by kea

## Pull Request Checklist

- [ ] The Certbot team has recently expressed interest in reviewing a PR for this. If not, this PR may be closed due our limited resources and need to prioritize how we spend them.
- [ ] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `main` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [ ] Include your name in `AUTHORS.md` if you like.

2025-01-03 22:19 UTC, ohemorange requested changes

2025-01-03 22:19 UTC, ohemorange commented on certbot/docs/using.rst
> +================== ==== ==== =================================================================
Is there a reason the lines defining the table were adjusted? I'd rather keep commit history clean if not.

2025-01-04 15:20 UTC, kea commented on certbot/docs/using.rst
> +================== ==== ==== =================================================================
Yes, the row I've added is 2 characters longer than the previous longest row.

2025-01-06 20:37 UTC, ohemorange approved these changes

2025-01-06 20:37 UTC, merged