RFC: Add --dry-run-deploy-hooks to run the deploy-hooks on dry runs
certbot/certbot pull request #8242
Opened 2020-08-30 14:24 UTC by Flowdalic

Now "certbot renew --dry-run --dry-run-deploy-hooks" can be used to
run the deploy-hooks without certbot actually contacting the
LetsEncrypt API. This can be useful when developing/modifying
deploy-hooks, in order to prevent running into LE's rate limiting.

Fixes #5658.

2020-09-01 20:34 UTC, adferrand requested changes
Hello @Flowdalic! Thanks a lot for your PR.

It is an interesting proposition, quite simple, but it has some flaws. In particular, the association of these two flags will not work on a `certonly` command, since the `certonly` command in dry run mode does not write any certificate on the filesystem, so the deploy hooks will fail.

More generally testing the certbot issuance process itself with a dry run, and testing the deploy hooks logic, are two different concepts. This is a part of my argumentation in https://github.com/certbot/certbot/issues/5658. @bmw also suggested a design proposition that respects that approach in https://github.com/certbot/certbot/issues/5658#issuecomment-494570998, and also proposed to make a +1 vote on the general design of this functionality before starting the implementation.

I propose we do that first.

2020-09-02 07:08 UTC, Flowdalic commented
> the association of these two flags will not work on a `certonly` command,

That may be very well true, [but I deliberately marked `--dry-run-deploy-hooks` only for the `renew` command](https://github.com/certbot/certbot/pull/8242/files#diff-fc3606eecd5eed97cf47df9f30803ab3R171). I don't have any intent or desire that `--dry-run-deploy-hooks` works with `certonly` too.

Maybe I should re-iterate my scenario and what drove me to create this issue in the first place: When I make a change to a deploy hook script, I want to test the change. Right now I can only use `certbot renew`, *without* `--dry-run` because the deploy hooks are not invoked if `--dry-run` is given. Now the issue is that every time I call `certbot renew` a real API request is made and a new certificate is created. The latter may not be much of an issue (besides being wasteful), but the former means that I will run into LE's API rate limiting after a few successize `certbot renew`s. And that limit can easily be hit if you make larger changes to a deploy hook script. Using 
```
certbot renew --dry-run --dry-run-deploy-hooks
```
*does what I need* in that case. It is really that simple.

> More generally testing the certbot issuance process itself with a dry run, and testing the deploy hooks logic, are two different concepts.

Totally agree. I am only interesting in testing the deploy hooks for existing certificates.

> This is a part of my argumentation in #5658. @bmw also suggested a design proposition that respects that approach in [#5658 (comment)](https://github.com/certbot/certbot/issues/5658#issuecomment-494570998), and also proposed to make a +1 vote on the general design of this functionality before starting the implementation.

I fear I have no idea what this eventually involves. Especially the the last part of "make a +1 vote on the general design".

Surely something like `certbot run-deploy-hooks` would be just as fine. My PR currently adds another flag (`--dry-run-deploy-hooks`) that changes the behavior of an existing flag (`--dry-run`) if used on a particular command (`renew`). One could certainly argue that it is a bit verbose, but it does what I want (and it does not mean that we can't add a `run-deploy-hooks` shortcut later on). Also note that, judging from the upvotes of this issue, others are also looking for this: [this is the most upvoted issue of certbot](https://github.com/certbot/certbot/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) right now. But since I don't now what "respecting that approach" and "making a +1 vote on the general design" actually means, I am stuck on how to proceed from here.

I was actually hoping for some feedback about how I made the changes. But I am not sure if you question the whole fundamental idea of them.

2020-09-02 17:04 UTC, adferrand commented
Indeed I was not clear enough. This feature is in the "let's agree on its general design" step. In #5658 @bmw proposed a design. We are not expecting either several people participating in the discussion saying there are fine with this design, and we implement it that way, or an argumentation on why the design is not good enough, and something else should be done.

More specifically on your PR indeed, it is another proposition. Let's first validate or invalidate what is proposed in #5658.

On your PR what is bother me a little is that indeed, the flag covers a really specific use case, which are dry run renewals. While @bmw proposition allows to run it in various situation, including certificates generated from real calls, and constraint all the added complexity into one single subcommand.

2020-09-02 17:20 UTC, Flowdalic commented
> On your PR what is bother me a little is that indeed, the flag covers a really specific use case, which are dry run renewals. While @bmw proposition allows to run it in various situation,

I could be wrong, but it appears this is going to drift if into a large "big picture" discussion, while I believe a lot of certbot users would be already pretty happy, me included, if they could run the deploy-hooks without an actual cert renewal (which is what this PR is about).

Don't get me wrong. Working on the general design, the big picture, and a good user experience is essential. But I, as drive-by contributor, usually do not have the resources to participate in that. I have an issue with certbot that bothers me *since years*, and I believe this PR fixes it. But I am not going to pursue this further because I don't have the resources to work on the general design. Instead, I guess I'll go with [asdil12's suggestion and comment out the few offending lines](https://github.com/certbot/certbot/issues/5658#issuecomment-580922495), every time I work on a deploy hook. :frowning:

2020-09-06 12:26 UTC, adferrand commented
I understand your approach, since for a free contribution with time constraints, it seems quite decent to focus on the specific problems you encountered, and it is already more than expected to propose a patch for them instead of just reporting about it.

However you have to consider the number of people using Certbot, and the very limited resources of Certbot maintainers. For instance I do that on my part time, like several people here. So we need also to reduce at maximum the future maintenance burden that any feature integrated in Certbot will add. In that extent, we are tending to accept features with the widest scope.

I am really convinced that a specific subcommand approach will significantly widden the scope of your PR, while not being significantly more complex than what you did here. It would be really about something like registering a new subcommand, requiring at least one `--cert-name` flag to be set along with it, and call the relevant method in the `certbot._internal.hooks` module that will do all the heavy lift at that point.

2020-09-07 20:34 UTC, Flowdalic commented
> requiring at least one `--cert-name` flag to be set along with it

I wonder why you would want that requirement. Sure, for some cases it would probably be nice to restrict the dry run of the hooks to certain certificates, but I, for example, would want to dry run the deploy-hooks for all certificates. Besides, I don't even know what certbot considers a certificate name.

> In that extent, we are tending to accept features with the widest scope.

It appears to me that the drawbacks of this policy, namely reduced contributions, potentially outweigh its envisioned advantages. At least in this particular case. I am also not sure if there is an increased maintenance burden by accepting the PR as is. I would agree that adding a new feature without unit tests would cause an increased maintenance effort. But since there chances are dim that this gets accepted, I am not incentivized to write unit tests for this.

Be that as it may, my way ends here (at least for now).

2020-09-10 22:13 UTC, adferrand commented
Ok, very sorry we could not find a consensus here. I will close the PR. The reference stays in #5658, so if you or someone else is available to continue the work, do not hesitate to open a new PR!

2020-09-10 22:13 UTC, closed without merging