Simplify/document snap creation
certbot/certbot pull request #8404
Opened 2020-10-23 23:26 UTC by ohemorange

This PR adds the following documentation improvements to fix https://github.com/certbot/certbot/issues/7958:

- Simplify building external plugins
- Separate out certbot snap instructions from plugin instructions
- Mention that dnsimple is just an example for the plugin instructions
- Mention remote build for other architectures
- Mention snap doc exists elsewhere in developer guide (`contributing.rst`)

We could more neatly create the constraints file, as described in https://github.com/certbot/certbot/issues/8100, but what I did here achieves the goal of making it easier for someone building the snaps manually, since we probably do want to re-generate everything anyway. I think improving it for its own sake can come later.

Also, remote build doesn't seem to be launching the build when I tested the instructions, not sure what's going on there. I was going to wait and see if it works when azure tries.

2020-10-26 18:32 UTC, bmw commented
Closing and reopening to fix the CI status checks.

2020-10-26 22:14 UTC, bmw requested changes
Thanks a lot for working on this!

> Also, remote build doesn't seem to be launching the build when I tested the instructions, not sure what's going on there.

I think what's going on here is this command is really slow if you don't have a clean clone of our repo. `snapcraft` sends everything under your CWD to Launchpad and we often have things like multiple virtual environments (each of which is ~200MB), multiple clones of the repo under `releases/` or `tests/letstest/`, etc.

You can see this by running `snapcraft remote-build` directly with a command like `snapcraft remote-build --build-on=amd64` from the root of our repo to build the Certbot snap. On a clean clone on my laptop, in about a minute it prints:
```
Packaging sources for certbot...
Packaging sources for shared-metadata...
Sending build data to Launchpad... (https://bradmwarren:<token>@git.launchpad.net/~bradmwarren/+git/snapcraft-certbot-06e0c4/)
Enumerating objects: 12, done.
Counting objects: 100% (12/12), done.
Delta compression using up to 4 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (12/12), 59.22 MiB | 938.00 KiB/s, done.
Total 12 (delta 1), reused 0 (delta 0), pack-reused 0
To https://git.launchpad.net/~bradmwarren/+git/snapcraft-certbot-06e0c4/
 * [new branch]      HEAD -> master
If interrupted, resume with: 'snapcraft remote-build --recover'
Building snap package for amd64. This may take some time to finish.
```
In the clone of the Certbot repo I normally use it hangs on the earlier steps much longer.

Assuming this was the problem for you, I think adding a sentence about this to our docs is a good idea.

2020-10-26 23:17 UTC, ohemorange commented
Ah yes, that's almost certainly what it was, running the raw command now. I did not know this, I'll add a sentence about that!

2020-10-26 23:17 UTC, ohemorange commented on certbot/docs/contributing.rst
> +https://github.com/certbot/certbot/tree/master/tools/snap.
great idea!

2020-10-26 23:18 UTC, ohemorange commented on tools/snap/generate_dnsplugins_postrefreshhook.sh
> +#   bash generate_dnsplugins_postrefreshhook.sh certbot-dns-dnsimple
I'll do it as `tools/snap/` for ease of copy-pasting!

2020-10-26 23:19 UTC, ohemorange commented on tools/snap/README.md
> +
Oh, I'd actually assumed that you had to authorize it for each one you're building, this suggestion is much better!

2020-10-26 23:46 UTC, ohemorange commented
Here's the new `contributing.rst` section; the link works.

![Screenshot from 2020-10-26 16-46-16](https://user-images.githubusercontent.com/1227205/97240183-d0ce6b00-17aa-11eb-98a8-10564cece9c6.png)

2020-10-27 17:22 UTC, bmw approved these changes
Looks great! Thanks again for grabbing this.

2020-10-27 17:22 UTC, merged