Fix changelog typo
certbot/certbot pull request #8488
Opened 2020-12-01 20:53 UTC by bmw

The changelog will be incorrect for the 1.10.0 tag and release, but we can and I think we should fix it going forward.

2020-12-01 21:26 UTC, alexzorin requested changes
Shall we also fix the lonesome trailing `*` in the *Changed* section?

2020-12-01 21:29 UTC, bmw commented
We might as well!

2020-12-01 21:56 UTC, alexzorin approved these changes

2020-12-01 21:57 UTC, merged

2020-12-02 09:19 UTC, atombrella commented
This needs to be ported to the 1.10.x branch!