test: certbot-ci crash due to no p521 on boulder
certbot/certbot pull request #8602
Opened 2021-01-12 07:23 UTC by alexzorin

The bugfix in #8598 added an integration test to request a certificate
for an EC P-521 key, which is unsupported when ACME_SERVER=boulder,
failing our nightly integration tests.

---

Rather than branching on `context.acme_server` in `test_renew_with_ec_keys` or breaking out a separate integration test for E2E P-521 issuance, I have chosen to replace the coverage of the bug with a unit test. If it is important to have an E2E test of P-521 issuance, I'd be happy to re-add it.

2021-01-12 09:25 UTC, adferrand requested changes
Why do you want to avoid to branch on `context.acme_server` value? For the record, it is something already used in `test_ocsp_must_staple`.

2021-01-12 09:30 UTC, alexzorin commented
>Why do you want to avoid to branch on context.acme_server value? For the record, it is something already used in test_ocsp_must_staple.

To keep things easy to read. `test_ocsp_must_staple` is clean because it can use `pytest.skip`, but in `test_renew_with_ec_keys` we would have to branch the `secp521r1` logic and then also keep track of the count for `assert_cert_count_for_lineage`. I didn't like having so much state. But I will admit it's a taste thing.

2021-01-12 09:41 UTC, adferrand commented
I have two things in mind:
* _integration_ (technically more _system_ here by the way) tests are superior to any unit test for a given feature (but harder to achieve)
* a test should not have more than one feature to assert

The spirit of `test_renew_with_ec_keys` is more about testing the feature "having an EC certificate" and "handle properly EC key migration (arguably, already two features), than testing that each EC curve is working.

What about moving the test of `secp521r1` curve on a dedicated test method and properly skip it if needed?

2021-01-12 09:51 UTC, alexzorin commented
I agree. I suppose this will happen when coverage for different curves comes incidentally via other tests. I will add an E2E test for different curves explicitly.

2021-01-13 00:07 UTC, bmw approved these changes
Thanks again for jumping on this you two.

The test changes here seem good to me and I'd like to get tests on `master` fixed so I'm merging this, but please follow up with issues/PRs if you think there are other changes we should make here.

2021-01-13 00:08 UTC, merged

2021-01-13 00:14 UTC, adferrand commented
No it is ok for me, I was about to approve it anyway.

2021-01-13 00:15 UTC, bmw commented
Ah sorry. At a little after 1AM, I figured you'd be a asleep :smile: