Fix incompatibility with lexicon >= v3.6.0
certbot/certbot pull request #8819
Opened 2021-05-03 08:49 UTC by coldfix

Hi,

this resolves the following error in `dns_common_lexicon.py`:

```
  File "/usr/lib/python3.9/site-packages/certbot/plugins/dns_common_lexicon.py", line 48, in add_txt_record
    self.provider.create_record(type='TXT', name=record_name, content=record_content)
TypeError: create_record() got an unexpected keyword argument 'type'
```

The variable `type` parameter was renamed to `rtype` more than [2 years ago](https://github.com/AnalogJ/lexicon/commit/74b70b1efaf87a9a8eb0bbe901f05fb8013c88ca) ([v3.1.0]), and has been deprecated since. The old form has been removed [about a month ago](https://github.com/AnalogJ/lexicon/commit/174cf1cb13d38133475ee6d87d7a2f73aa0c0941) (v3.6.0) and now triggers a `TypeError`.

Since the renaming was done more than 2 years ago, I think it's safe to simply rename here as well (without adding compatibility `try ... except ...` clauses).

2021-05-03 19:57 UTC, mnordhoff commented on certbot/CHANGELOG.md
> +* Fix incompatibility (TypeError) with lexicon >= v3.6.0
Should this note that it's breaking backwards compatibility with <3.1.0?

2021-05-04 08:16 UTC, coldfix commented
If you prefer, it's also possible to stay compatible with both versions by using positional arguments. This would make the `delete_record` a bit more weird, though, since it requires passing a `None` in first position:

```python
delete_record(None, 'TXT', ...)
```

2021-05-05 22:09 UTC, adferrand requested changes
On top of my suggestion for the changelog, you need to update also the `setup.py` and `local-oldest-requirements.txt` files of all DNS plugins that rely on Lexicon, in order to declare that now `dns-lexicon>=3.1.0` is required (for the `setup.py`), or `dns-lexicon==3.1.0` will be used (for `local-oldest-requirements.txt`).

2021-05-05 22:09 UTC, adferrand commented on certbot/CHANGELOG.md
> +  compatibility with lexicon < v3.1.0
In fact, I think it is more important to say that Lexicon >= 3.1.0 is now required, and optionally say that it is to fix compatiblity with 3.6.0 and higher. The lower bound is the info you want to keep in the long term.

2021-05-05 23:08 UTC, coldfix commented
Hi, thanks for the comments! The constraints are now updated as requested in all but one case:

I wasn't sure how the `tools/oldest_constraints.txt` is structured (why is `dns-lexicon` listed under *Ubuntu Bionic constraints*, and if I change it, would I have to move it somewhere else?)

2021-05-07 21:16 UTC, coldfix commented
Done, thanks. As far as I understand the `local-oldest-requirements.txt` serve to override requirements from `oldest_constraints.txt`, so I have removed the dns-lexicon lines from where it was mentioned, since none of them was specifying a newer version.

2021-05-12 22:52 UTC, adferrand requested changes
One last thing, could you move the changelog entries you added in the `1.16.0` section of `CHANGELOG.md`?

2021-05-13 07:53 UTC, coldfix commented
Done, and rebased on current master.

2021-05-16 13:03 UTC, adferrand approved these changes
This LGTM! Thanks a lot!

2021-05-16 13:03 UTC, merged

2021-05-16 14:50 UTC, nidomiro commented
When will this fix be available in a new version of certbot-dns-ovh?
This issue is currently blocking me.

2021-05-16 16:57 UTC, nidomiro commented
Here is a workaround until 1.16.0 will be published:
instead of installing `certbot` and `certbot-dns-ovh` via pip, install `git+https://github.com/certbot/certbot.git@bc23e07ee5c144aa9b1d5cf9e0ba303d9e91a695#subdirectory=certbot` and `git+https://github.com/certbot/certbot.git@bc23e07ee5c144aa9b1d5cf9e0ba303d9e91a695#subdirectory=certbot-dns-ovh`.

2021-05-16 21:28 UTC, coldfix commented
@nidomiro Or just downgrade `pip install dns-lexicon==3.5`

2021-05-18 17:06 UTC, mstyne commented
I had to go all the way back to `dns-lexicon==3.1.0` to get things working again.