[Windows] Cleanup Certbot pkg dir before installing to avoid dependencies conflicts
certbot/certbot pull request #8836
Opened 2021-05-08 12:47 UTC by adferrand

Fixes #8824

This PR makes the installer first delete (if exist) the previous `pkg` directory in the Certbot installation in order to avoid dependencies conflicts when a new version of Certbot (with new versions of dependencies) is intaller other an existing one.

I took the simplest approach here, which is to delete specifically the directories known to create conflicts, instead of more complex approaches that involve to factor in some way the complete uninstaller logic. This is because the complexity added without a clear improvement does not worth it in my opinion. More specifically:
* factorizing in some way the uninstaller section in the NSIS template make the installer use any potential new logic of a new installation of Certbot instead of the one applying for the current installation, and may create unexpected errors during installation or at runtime
* calling the existing `uninstaller.exe` would be better, but I could not find a proper way to let NSIS wait for the actual end of the uninstall logic, and again may create unexpected errors during installation or at runtime

2021-05-12 20:02 UTC, bmw commented
Did you see https://stackoverflow.com/questions/4676898/how-to-execute-an-nsis-uninstaller-from-within-an-another-nsis-installer-and-wai? There are some comments saying the most upvoted answer doesn't work, however, that exact line is included in the NSIS documentation linked there. If it works and there's a way to conditionally run the uninstaller only if it exists, is there any reason that solution shouldn't be preferred?

If we take this approach, I wonder if it might be worth suggesting the change upstream as a fix for https://github.com/takluyver/pynsist/issues/66. The maintainer suggested it as a possible yet inefficient option 5 years ago so I wonder if they'd accept it upstream so they can finally close that issue and we can maintain a smaller diff to our `.nsi` file.

2021-05-12 21:11 UTC, adferrand commented
Yes I saw this stackoverflow proposition, and noticed as other did before that the NSIS installer returns immediately instead of waiting for the uninstall process to finish.

2021-05-12 23:33 UTC, bmw commented
That's unfortunate. I confirmed this works though so if you add a changelog entry about this I think we can merge this.

2021-05-17 16:11 UTC, bmw requested changes
Other than my minor suggested tweaks to the changelog, this LGTM!

2021-05-17 16:11 UTC, bmw commented on certbot/CHANGELOG.md
> +* Windows installer now cleans up old Certbot dependencies packages
```suggestion
* Windows installer now cleans up old Certbot dependency packages
```

2021-05-17 16:11 UTC, bmw commented on certbot/CHANGELOG.md
> +  before installing the new ones to avoid versions conflicts.
```suggestion
  before installing the new ones to avoid version conflicts.
```

2021-05-17 17:22 UTC, bmw approved these changes

2021-05-17 17:22 UTC, merged