Deprecate usage of IConfig as a singleton in Certbot
certbot/certbot pull request #8869
Opened 2021-05-26 21:25 UTC by adferrand

As discussed in #8835, this PR deprecates the usage of `config` as a singleton in Certbot. Concretely, it means that `zope.component.getUtility` is not used in the Certbot codebase anymore to retrieve the `config` object, which is passed as regular function argument instead.

The calls of `zope.component.provideUtility` for `config` are kept for compatibility, and appropriate deprecation warnings are emitted for third parties.

2021-05-26 21:30 UTC, adferrand commented
Note that this PR changes the public API for `certbot.crypto_util.init_save_key` and `certbot.crypto_util.init_save_csr`). These changes are technically forward compatible because new parameters are added as named parameters with default values. These values are also the default one in the `config` object.

2021-05-27 17:44 UTC, bmw commented
Thanks for working on this! I have two design changes I wanted to suggest:

1. Instead of monkey patching `zope.component`, what do you think about warning on accesses of `interfaces.IConfig` like I suggested at https://github.com/certbot/certbot/pull/8835#issuecomment-843396347? I think this probably shouldn't be added now and instead would be added as part of the `zope.interface` work. I personally like this approach better because I worry that monkey patching is somewhat fragile and think we should probably be warning about the interface going away anyway so it simplifies the code.
2. I think the API changes made to the two `crypto_util` functions is somewhat aggressive. I feel this way because the current configuration values are no longer respected and [strict_permissions actually defaults to `False`](https://github.com/certbot/certbot/blob/3640b8546e137916fd9e6c28b1ecb7b2faaffc1d/certbot/certbot/_internal/constants.py#L68). Instead, what do you think about either:

a) Making two new functions named something like `create_save_{csr,key}` that accepts parameters like you have here while `init_save_*` would raise deprecation warnings telling people to use the create functions, grab the values from the global config using `zope`, and then call the new functions.

b) Making the default values of the parameters to `init_save_*` `None` and if they are `None`, raise a warning saying these values must be set in a future release and grab the current value from the global config object.

What do you think?

2021-05-27 17:57 UTC, adferrand commented
Indeed on the scope of `zope.interface`it makes more sense to emit warnings when the `certbot.interfaces` module is imported. My initial approach was to reuse this module for the ABC classes, making the deprecation  logic a little trickier to implement, but we can certainly circumvent that or use a new module name.

For the public API, I have a slight preference for solution b, because it avoids to add more content (functions) to the API, and the names `init_save_*` are quite appropriate and should be kept if possible.

2021-05-27 19:43 UTC, adferrand commented
After some discussions, I prefer to go with option a for the public API, because the behavior induced by solution b on existing deprecated options is not obvious and harm usability.

2021-05-28 16:55 UTC, bmw requested changes
My only comment other than my small documentation suggestions that I wrote inline is I think it'd be nice to provide simple unit tests of the `init_save*` functions. I was imagining something like asserting that a warning is raised and and a call is made to `generate_*` as we expect. You can probably talk me out of writing these tests if you really don't want to do it, but due to the dynamic nature of Python and the fact I think writing these tests should be pretty easy, I personally think it's worth it.

2021-05-28 16:55 UTC, bmw commented on certbot/certbot/crypto_util.py
> +        (POSIX mode 0600).
I think a more accurate description here would be something like:

> If true and key_dir exists, an exception is raised if the directory doesn't have 0700 permissions or isn't owned by the current user.

2021-05-28 16:55 UTC, bmw commented on certbot/certbot/crypto_util.py
> +        permissions (POSIX mode 0600).
I think a more accurate description here would be something like:

> If true and path exists, an exception is raised if the directory doesn't have 0755 permissions or isn't owned by the current user.

2021-05-28 16:55 UTC, bmw commented on certbot/certbot/_internal/client.py
> +        :param interfaces.IConfig config: current Certbot configuration
```suggestion
```

2021-05-28 16:55 UTC, bmw commented on certbot/certbot/crypto_util.py
> +    :param boolean must_staple: If true, include the TLS Feature extension "OCSP Must Staple"
```suggestion
    :param bool must_staple: If true, include the TLS Feature extension "OCSP Must Staple"
```

2021-05-28 16:55 UTC, bmw commented on certbot/certbot/crypto_util.py
> +    :param boolean strict_permissions: If true, the CSR file will be saved with strict
```suggestion
    :param bool strict_permissions: If true, the CSR file will be saved with strict
```

2021-05-28 16:55 UTC, bmw commented on certbot/certbot/crypto_util.py
> +    :param boolean strict_permissions: If true, key will be saved with strict permissions
```suggestion
    :param bool strict_permissions: If true, key will be saved with strict permissions
```

2021-05-28 16:55 UTC, bmw commented on certbot/certbot/crypto_util.py
> +    .. deprecated:: 1.16.0
Nice! I never knew about this syntax. Thanks for adding this.

2021-05-28 19:17 UTC, bmw approved these changes
LGTM!

2021-05-28 19:17 UTC, merged