acme: deprecate ACMEv1 client classes
certbot/certbot pull request #8931
Opened 2021-07-03 00:07 UTC by alexzorin

Adds pending deprecations to:
- acme.client.Client
- acme.client.BackwardsCompatibleClientV2

Adds a warning to Certbot when a v1 server is detected.

----

![image](https://user-images.githubusercontent.com/311534/124337487-35698180-dbe6-11eb-9ebd-9c24d006be96.png)

Fixes #8929.

2021-07-03 20:20 UTC, atombrella submitted a review, later dismissed
LGTM

2021-07-15 22:26 UTC, ohemorange requested changes
Super tiny nit, otherwise lgtm!

2021-07-15 22:26 UTC, ohemorange commented on certbot/certbot/_internal/client.py
> +                                user_agent=determine_user_agent(config))
*extremely* minor nit, but to keep the git blame accurate, want to put the spaces back?

2021-07-15 22:36 UTC, ohemorange approved these changes

2021-07-15 22:50 UTC, merged