Emit deprecation warnings for Zope interfaces
certbot/certbot pull request #8970
Opened 2021-08-04 13:25 UTC by adferrand

This PR is a follow-up of #8950, that ensures deprecation warnings are emitted to developers when they try to use the old Zope interfaces. It uses the same approach than for TLS-SNI-01 related objects in the acme project (see #6859).

2021-08-12 23:48 UTC, alexzorin approved these changes
LGTM, seems to do the right thing with third party plugins

2021-08-12 23:51 UTC, alexzorin requested changes
Oops, actually, I think we need a CHANGELOG entry for this.

2021-08-14 19:58 UTC, adferrand commented
Hello @alexzorin, this is done.

2021-08-14 21:06 UTC, alexzorin approved these changes

2021-08-14 21:06 UTC, merged