certbot-dns-rfc2136: catch error when a hostname is being used for `dns_rfc2136_server`
certbot/certbot pull request #8990
Opened 2021-08-15 10:02 UTC by osirisinferi

Currently, if a hostname is used for `dns_rfc2136_server`, dnspython raises a `dns.exception.SyntaxError` internally in `ipv4.py` which is propogated to certbot-dns-rfc2136 through a `ValueError` in `inet.py`. Previously, this was catched by the generic exception at the end of `_query_soa()` without providing much information to the user.

This small PR adds a separate check for the `ValueError` raised by dnspython when a hostname has been entered instead of the required IP address. You can see in the [dns.query.tcp() documentation](https://dnspython.readthedocs.io/en/latest/query.html#tcp) an IP address is required.

I thought about adding a test for this, but I was unsure on how to proceed: in the current `dns_rfc2136_test.py` the `dns.query.tcp()` function is mocked out and consequently hardcoding a mocked exception and checking for that same exception doesn't make much sense to me..

2021-08-19 07:31 UTC, alexzorin requested changes
Great! Improving the error message here is definitely a good idea.

I am very skittish about assuming why a blank `ValueError` was raised in this way. There have been some places in Certbot where this kind of thing has produced incorrect advice before. I think the `dns` library is letting us down here and we need to work around it.

I propose an alternative: repurpose `_validate_algorithm` to both validate the algorithm and also validate the `server` with `dns.inet.is_address`. This function uses the same logic that eventually produces the `ValueError` that we see currently.

It should be easier to test, too.

2021-08-19 08:48 UTC, osirisinferi commented
Hm, makes more sense indeed. I looked at some `inet_aton()` functions (not sure if I looked in the pythondns library tho), but for some reason I didn't see the `is_address()` function (which of course is the easiest method to use)? And therefore just uses the ValueError :stuck_out_tongue: /lazy..

If I have some spare time I'll rebuild this PR :slightly_smiling_face:

2021-08-19 19:08 UTC, osirisinferi commented
Made the change :slightly_smiling_face: 

Also, I noticed something: why isn't the credentials option "algorithm" added to the list of required credential options in `_configure_credentials()`? To me, it would make more sense to add "algorithm" to `_configure_credentials()` and remove the `if algorithm:` check from `_validate_algorithm`. That change would put the check for the existance of the option to the place where it actually belongs, with proper errors raised if it's missing, and consequently the `if algorithm:` could be removed.

2021-08-19 21:13 UTC, alexzorin commented
I assume `algorithm` is this way because it is intended to be optional, defaulting to MD5:

https://github.com/certbot/certbot/blob/435ae075a52072b65c25add70c029728e7a1c3be/certbot-dns-rfc2136/certbot_dns_rfc2136/_internal/dns_rfc2136.py#L88-L89

Thanks for the changes, I'll review it soon.

2021-08-19 21:17 UTC, osirisinferi commented
> I assume `algorithm` is this way because it is intended to be optional, defaulting to MD5

Uch, nevermind my remark indeed, my thought process was quite off the rails when looking at the logic. Missed the fact that if the first `if` statement would be False it would never raise the exception. For some reason my brain thought it would...

2021-08-22 23:38 UTC, alexzorin approved these changes
Great! The error message is *so* much better now. Thanks.

2021-08-22 23:38 UTC, merged