Add `--source-address` option to certbot
certbot/certbot pull request #9021
Opened 2021-09-04 22:48 UTC by osirisinferi

Fixes #3489

Lightly based on #6007.

A few remarks I have:

* Currently, testing for a valid address is done in the argument parser. What about `cli.ini`?
* `acme` raises `ValueError`/`requests.exceptions.ConnectionError` (IPv4 resp. IPv6) if urllib3 cannot bind the source address (ultimately this stack of exceptions starts with an `OSError`). Currently, the `acme` library does not catch these errors. Locally, I modified certbots `client.py` to catch and reraise the errors as OSError, but I'm not sure if this useful at all.. Also, not sure how to write tests for them.. Mock requests or urllib3 and have some kind of mock exception raised? Also, shouldn't that be done in `acme` instead of certbot?

2021-09-04 22:56 UTC, osirisinferi commented
Not sure where the `ModuleNotFoundError: No module named 'dns'` error in some of the tests comes from...

2021-09-05 08:35 UTC, alexzorin commented
> Not sure where the ModuleNotFoundError: No module named 'dns' error in some of the tests comes from...

That's the module you used in #8990, right?

Although `certbot-dns-rfc2136` depends on `dnspython`, the `certbot` module on its own does not. Using that module/function here would require adding a new dependency to the main `certbot` module. 

Personally I think it would be good to avoid adding new dependencies here, depending on what the benefit is.

No comment on the rest of the PR, I'm going to leave this in the triage queue for now.

2021-09-05 09:38 UTC, osirisinferi commented
> That's the module you used in #8990, right?

Correct, worked nicely there, so I thought: let's use it here too.



> Although `certbot-dns-rfc2136` depends on `dnspython`, the `certbot` module on its own does not. Using that module/function here would require adding a new dependency to the main `certbot` module.

Hmm, interesting! I didn't think of that, because `py3-cover` worked like a charm. Perhaps that test suite pulls in `dnspython`, for use in the DNS plugin, also for `certbot` itself? I dunno.. 



> Personally I think it would be good to avoid adding new dependencies here, depending on what the benefit is.

I think testing user input for validity is always a good idea, but I understand adding an entire dependency for just a single function is undesirable.

The idea behind [`dns.inet.is_address`](https://dnspython.readthedocs.io/en/latest/_modules/dns/inet.html#is_address) is fairly simple and *probably* could work with regular, build-in Python functions too.

That said, dnspython currently is licensed under the [ICS License](https://github.com/rthalley/dnspython/blob/e863a2cb6837b8c0339f1dba803230d1c093d798/LICENSE) which demands adding the copyright notice and permission notice to "all copies". However, not sure if I'm "copying" the dnspython code if I'm just using the `try`/`except` concept with other, regular built-in Python functions. It kinda looks the same, but isn't? And the `try`/`except` concept is of course very generic, so I'm *guessing* it isn't a legal infringement if you'd ask me? But I'm not a lawyer :stuck_out_tongue:

2021-09-08 23:08 UTC, alexzorin requested changes
This looks pretty good. A couple of changes so far.

One thing I am unsure about is whether we want to make the source address part of the certificate renewal parameters. The thing about #3489 is that I don't *really* understand the use case. Does the user need to be able to vary source address based on lineage? Let's Encrypt doesn't grant  rate limit exemptions based on IP, does it? I will ask the team about this.

2021-09-09 20:38 UTC, osirisinferi commented on certbot/certbot/_internal/cli/cli_utils.py
> +                invalid_address = True
Cool, I did not know that.

2021-09-10 19:08 UTC, bmw commented
> One thing I am unsure about is whether we want to make the source address part of the certificate renewal parameters. The thing about #3489 is that I don't really understand the use case. Does the user need to be able to vary source address based on lineage? Let's Encrypt doesn't grant rate limit exemptions based on IP, does it? I will ask the team about this.

Yeah. Thanks for yet another PR Osiris, but I don't think we want this. It complicates Certbot's code and CLI for a strange use case requested by at most 2 people (and only 1 if you don't count the 👍 on the initial post).

For that reason, I'm closing this PR for now, but feel free to comment if you'd like to talk about this more.

2021-09-10 19:08 UTC, closed without merging

2021-09-10 19:48 UTC, osirisinferi commented
Just a small question: why was the feature added to the `acme` library if it's an unwelcome addition to certbot?

2021-09-10 22:07 UTC, bmw commented
> Why was the feature added to the `acme` library in the first place if it's an unwelcome addition to certbot? Or just a change of opinion?

I think this was largely just a change of opinion.

To say a little about why though, I think I was influenced by pde's initial comment that we'd accept a PR for this and in the past I was more idealistic about our ability to do and maintain all the things in Certbot. Nowadays, I'm much more realistic/pessimistic and think we should be much more selective about the work we do. This is both because we are still stretched quite thin and because I think it's worthwhile to try and spend our time where we expect it'll have the largest impact.

> Also, perhaps it's a good idea to go through the issue list and close stuff as #wontfix if applicable so people don't end up wasting time on things like this.

I agree. We have an internal document of larger, high priority projects and this is already one on the list.

In the meantime, if you'd like to keep working on Certbot and avoid this problem in the future, feel free to check with us on GitHub or Mattermost ahead of time about a feature you want to work on.

> Also a second thing I noticed: in this PR two members of the certbot team act rather differently, which is kinda confusing to me?

I'm not entirely sure what you mean, but if you mean Alex reviewing the PR and then me closing it, Alex with a fresh set of eyes (rightly) questioned pde and I's previous decision in #3489, asked the team about this, and I agreed that I don't think this feature makes sense for us. I think Alex slightly alluded to this in https://github.com/certbot/certbot/pull/9021#pullrequestreview-749680329, but hopeful this helps make things a little less confusing.