Added --timeout command line option
certbot/certbot pull request #9056
Opened 2021-10-05 11:30 UTC by moratori

Fixes #6513

Added --timeout command line option.
This option specifies the timeout value in seconds for obtaining a certificate  from Certificate Authority.
Default timeout value currently hard-coded as 90sec moved to constants.

## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

2021-10-07 22:31 UTC, alexzorin commented
Thank you for implementing this PR @moratori. I intend to review it shortly.

2021-11-28 09:48 UTC, moratori commented
@alexzorin 
I have fixed the issues you pointed out. I apologize it took so long time.
Could you please review it once again.

2021-11-28 20:50 UTC, alexzorin commented
Thanks, I'll try review this soon!

2021-11-28 23:45 UTC, alexzorin requested changes
Thanks. This is well written and seems to work as advertised.

Just some minor feedback about `certbot --help`.

2021-11-28 23:45 UTC, alexzorin commented on certbot/certbot/_internal/cli/__init__.py
> +        None, "--issuance-timeout", type=int,
Let's restrict this to positive values:

```suggestion
        None, "--issuance-timeout", type=nonnegative_int,
```

2021-11-28 23:45 UTC, alexzorin commented on certbot/certbot/_internal/cli/__init__.py
> +        None, "--issuance-timeout", type=int,
I have a feeling that we should make this flag appear in the `--help` topics for `all`, `certonly` and `run`:

```suggestion
        [None, "certonly", "run"], "--issuance-timeout", type=int,
```

2021-11-28 23:45 UTC, alexzorin commented on certbot/certbot/_internal/cli/__init__.py
> +    helpful.add(
One very minor thing: would you be able to move this entry lower, maybe below `--preferred-challenges`? 

`argparse` lists flags in the order they are added, and I think we should try keep the more important flags at the top.

2021-11-28 23:45 UTC, alexzorin commented on certbot/CHANGELOG.md
Excess newline:

```suggestion
```

2021-11-29 12:58 UTC, moratori commented
@alexzorin 
Thank you very much for the prompt review!
I think I have resolved all the comments I have received so far.
I would appreciate it if you could review again.

2021-11-29 21:16 UTC, alexzorin approved these changes
Thanks again.

2021-11-29 21:17 UTC, merged