Add typing to certbot.apache
certbot/certbot pull request #9071
Opened 2021-10-20 19:29 UTC by atombrella

I noticed that Python 2.7 support has been dropped from that module.

There are still things I don't really know how to do with `typing`, e.g., reference something from the module itself. `obj.Addr` is one example.

There are some irrelevant changes, that probably should go in separate PRs. f-string and the single `object` thing I removed.

## Pull Request Checklist

- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

2021-11-07 14:10 UTC, adferrand commented
@atombrella stay tuned on this PR. As soon as my PRs to fully type the `certbot` package, I will go back to your PR so that we implement the full typing for `certbot-apache`.

2021-11-07 19:05 UTC, atombrella commented
@adferrand Good :) I just pushed some updates. I'm currently not able to run `tox` locally (it fails with the `augeas` package).

2021-12-04 23:37 UTC, atombrella commented on certbot-apache/certbot_apache/_internal/obj.py
> +        )
I know this is unrelated to the typing. I can move it to a new PR?

2021-12-07 08:45 UTC, atombrella commented
@adferrand I've added a bunch more typing locally, and will try to get the tests to pass. Maybe we can merge this before Christmas :tada: It's rather tempting to do more clean-up in `certbot-apache` while doing this, e.g., use f-strings.

2021-12-07 08:51 UTC, adferrand commented
Hello @atombrella, I checked on my side the amount of potential work to type `certbot-apache`, and I also take into consideration the work required to type `certbot-nginx` in https://github.com/certbot/certbot/pull/9124: there is a tremendous amount of work.

So I would prefer that we separate the typing itself and the improvement of the code quality itself. So I can make several propositions for a strategy:
* I can do the typing since I did it for the rest of the code and you focus on the code quality in a separate PR
* you can continue on this PR and focus on typing alone, and then another PR for the code quality

What do you think?

2021-12-07 08:55 UTC, adferrand commented
I just looked at the latest commits, you added a lot of types. It would be a shame to loose this PR. So my favor is on continue to focus on the typing here and take the code quality later.

2021-12-07 09:45 UTC, atombrella commented
> Hello @atombrella, I checked on my side the amount of potential work to type `certbot-apache`, and I also take into consideration the work required to type `certbot-nginx` in #9124: there is a tremendous amount of work.
> 
> So I would prefer that we separate the typing itself and the improvement of the code quality itself. So I can make several propositions for a strategy:
> 
>     * I can do the typing since I did it for the rest of the code and you focus on the code quality in a separate PR

I have a bunch more stuff locally that I'll push. You have access to my branch, so it's possible I'll request some active help at some point. Annotating with types does indeed take a lot of time, especially fixing the errors/warnings from `mypy`.
 
>     * you can continue on this PR and focus on typing alone, and then another PR for the code quality

Yes. That's also why I opened #9114 which is now merged. Initially this PR was spawned from some contemplation to do TLS 1.3 only support, as [Mozilla SSL configurator](https://ssl-config.mozilla.org/#server=apache&version=2.4.41&config=modern&openssl=1.1.1k&guideline=5.6) has for the `Modern` option, but decided typing was also fun to do.

2021-12-15 15:44 UTC, atombrella commented
@adferrand I added loads more types today. I think it's ready to be reviewed, and looked over :) I use PyCharm, which still complains a bit a few places, but locally, `mypy` and `tox` seem happy. Please note that this is my first major `typing` project, so there are undoubtedly things to improve.

2021-12-15 20:17 UTC, adferrand commented on certbot-apache/certbot_apache/_internal/apache_util.py
> +def included_in_paths(filepath: str, paths: List[pathlib.Path]) -> bool:
I think `path` should be `List[str]` here.

2021-12-15 21:02 UTC, adferrand requested changes
Thanks a lot @atombrella, here is my review. I will do a second round once all checks pass.

2021-12-15 21:02 UTC, adferrand commented on certbot-apache/certbot_apache/_internal/configurator.py
> +    # pragma: no cover
I think this change makes the cover ignore directive a noop.

2021-12-15 21:02 UTC, adferrand commented on certbot-apache/certbot_apache/_internal/configurator.py
> +    ) -> List[Optional[challenges.HTTP01Response]]:
Given the interface, `perform` should return `List[challenges.HTTP01Response]`

2021-12-15 21:02 UTC, adferrand commented on certbot-apache/certbot_apache/_internal/configurator.py
> +    def _update_responses(self, responses: List, chall_response, chall_doer) -> None:
You can precise `List[challenges.HTTP01Response]` for `responses`.

2021-12-15 21:47 UTC, atombrella commented on certbot-apache/certbot_apache/_internal/augeasparser.py
> +    def set_parameters(self, parameters: List[str]):
https://docs.python.org/3/library/typing.html#typing.List Ah, I missed this :) `List` and `Iterable` are easy to mix up.

2021-12-15 21:48 UTC, atombrella commented on certbot-apache/certbot_apache/_internal/apache_util.py
> +def included_in_paths(filepath: str, paths: List[pathlib.Path]) -> bool:
Just to follow https://docs.python.org/3/library/typing.html#typing.List I'll do `Iterable`.

2021-12-17 12:12 UTC, atombrella commented on certbot-apache/certbot_apache/_internal/parsernode_util.py
> +def directivenode_kwargs(kwargs: Dict[str, Any]) -> Tuple[Any, Any, Any, Dict]:
I get a bunch of warnings when using `Mapping` :/

2021-12-17 19:27 UTC, atombrella commented
@adferrand While going through your remarks, I'm noticing some odd things in the code. One thing in particular is the mismatch with error handling, and returns. One good example is `def _create_vhost(self, path: str) -> Optional[obj.VirtualHost]:` which causes various warnings, because `make_vhost_ssl` in the `Configurator` has `ssl_vhost = self._create_vhost(vh_p)` which then expects a non-null object. There are still failures locally that I'm working my way through.

I'm noting down this as a future improvement idea: keyword-only arguments in different places of the module. It'll make some things easier and safer when passing arguments around. Python 3 introduced them in https://www.python.org/dev/peps/pep-3102/ Personally I enjoy them, and while recently getting a bit into GoLang, I was discussing with a previous colleague how useful this is in Python.

2021-12-29 08:39 UTC, atombrella commented on certbot-apache/certbot_apache/_internal/http_01.py
> +    def perform(self) -> List[Challenge]:
It's getting the data from `_set_up_challenges`, which returns `List[Challenge]`.

2021-12-30 20:44 UTC, atombrella commented
@adferrand I fixed some of the warnings. I'd like some active assistance to pushing to over the finish line. Currently there are some 30-something warnings.

2022-01-01 22:21 UTC, atombrella commented
```
certbot-apache/certbot_apache/_internal/parser.py:97: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "options"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:166: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "save_notes"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:191: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "save_notes"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:192: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "save"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:203: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "save_notes"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:225: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "save_notes"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:297: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "options"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:307: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "options"  [union-attr]
certbot-apache/certbot_apache/_internal/parser.py:316: error: Item "None" of "Optional[ApacheConfigurator]" has no attribute "options"  [union-attr]
```

This is one part of my heacaches with annotating the Apache plugin. There are loads of `return None` where I think it'd be more correct to throw an error instead.

@bmw @alexzorin @adferrand Could you please add the labels to this PR? `area: python`, `area: apache`.

2022-01-01 23:12 UTC, adferrand commented
Hello @atombrella. First thing first, I will be available again next week to review the state of the work you did here. But it seems that most of the issues are fixed now, we are almost there!

For the remaining issues, yes I have encountered a similar situation with the Nginx plugin. Basically, all there errors mean that if the plugin is not "prepared", it will not work. What is unfortunate with the current design is that this preparation is not part of the real Python object initialization, but is more like a lazy process called at a later time using the `prepare()` method. From what I understood it is done like this to be able to manipulate a reference of the plugin before it is actually used (eg for plugin selection).

This is something that `mypy` cannot understand, since there are higher level process ensuring that the actual logic of the plugin is not called before the plugin is prepared. We will have to help `mypy` by writing some exceptions. In the Nginx plugin, I tried to limit these exception as much as possible by writing them early in the plugin lifecycle so that we can suppose also very early that the critical variables are not `None` anymore.

2022-01-03 21:09 UTC, adferrand commented
@atombrella, some conflicts here since your cleanup in the Apache plugin code.

2022-01-09 22:40 UTC, atombrella commented
@adferrand rebased and fixed the conflicts in case you haven't noticed.

2022-01-19 11:35 UTC, adferrand commented
@atombrella as requested, I pushed some commits on your PR to solve the remaining errors.

2022-01-19 12:15 UTC, atombrella commented
@adferrand Thank you :) As you wrote, it doesn't seem like a massive amount of stuff you had to change :tada: 

When you merge, could you please edit the commit message inside the merge dialog so it's not full of the intermediate commit messages (obviously, just remember the `Co-Authored-By: ..`) ? It clutters `git blame`, and it's referenced in the PR.

2022-01-21 09:15 UTC, adferrand approved these changes
Full test campaign is passing. Types looks great. LGTM!

2022-01-21 09:15 UTC, merged

2022-01-21 09:16 UTC, adferrand commented
@atombrella I reduced the list of commits to only one significant, as you requested.