Improve assertions in certbot-apache tests.
certbot/certbot pull request #9131
Opened 2021-12-09 21:03 UTC by atombrella

Replacements inspired by flake8-assertive.

@adferrand As discussed in #9071 here's one part of some improvements that are probably good to get in. There are various odd asserts in the tests, which I've attempted to clean-up. There was some use for `is ...` where I think `equals` would be appropriate. I'll deal with possible test failures, and lint failures in the weekend. 

## Pull Request Checklist

- [X] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [X] Add or update any documentation as needed to support the changes in this PR.
- [X] Include your name in `AUTHORS.md` if you like.

2021-12-24 12:44 UTC, atombrella commented
@adferrand @bmw @alexzorin The tests are passing locally and on Azure DevOps, but the step for building the documentation does not pass. I'm not sure my changes caused this or not.

I tried to rewrite some of the assertions for lists, to use `len` to test for emptiness, rather than using `assertTrue`. There are some unrelated changes, mostly to put statements on one line. I'm not sure if there has been a 80 char limit on the lines at some point, or if that's just the coding style of some contributors.

2021-12-25 03:36 UTC, alexzorin commented
The test failure was caused by a random 502 from readthedocs, it passed on a second run.

2021-12-25 12:45 UTC, atombrella commented on certbot-apache/tests/dualnode_test.py
> -        self.assertTrue(cnode.primary is self.comment.secondary)
I was somewhat puzzled about `is` instead of `==` in these tests.

2022-01-01 23:21 UTC, adferrand requested changes
Globally I think this PR improves a lot the expressiveness of the code in the unit tests.

I would have one single question about the usage of `assertIs` when we are checking the truthiness of a variable. You changed several assertions from `self.assertTrue(booleanVariable)` to `self.assertIs(booleanVariable, True)`.

Don't you think that for this situation, keeping the dedicated `assertFalse`/`assertTrue` is more appropriate?

2022-01-02 13:40 UTC, atombrella commented
> Globally I think this PR improves a lot the expressiveness of the code in the unit tests.
> 
> I would have one single question about the usage of `assertIs` when we are checking the truthiness of a variable. You changed several assertions from `self.assertTrue(booleanVariable)` to `self.assertIs(booleanVariable, True)`.
> 
> Don't you think that for this situation, keeping the dedicated `assertFalse`/`assertTrue` is more appropriate?

I think for asserting boolean values, `assertIs` is the correct thing to use. `assertFalse`/`assertTrue` are to be used for checking for null/non-null values. That's at least the general advice given in the documentation: https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertTrue 

`self.assertEqual(post_loadmods, [])` is one my changes, from `assertFalse(post_loadmods)`. I think potentially both are fine to use, and a matter of style which you prefer.

2022-01-02 16:53 UTC, atombrella commented
`assertTrue(['a']), assertFalse([])` I can list other examples. `assertIs` checks for the actual value. Since we added annotations to certbot, I think this is a good argument for `assertIs`-changes, so we check for the returned boolean values.

2022-01-03 21:04 UTC, adferrand commented
For `assertTrue/assertFalse`, more about truthiness of falsiness values it seems from the documentation, but I got your point.

It is quite a similar situation for `assertEqual(post_loadmods, [])` vs `assertFalse(post_loadmods)` where the later would test for falsiness value, which includes in particular `None`, or any other falsiness value like `False` or `{}`, and then again `assertIs` is more accurate for assertions in the context of testing.

Thanks!

2022-01-03 21:05 UTC, adferrand approved these changes

2022-01-03 21:05 UTC, merged