Update generated CSRs to create V1 CSRs
certbot/certbot pull request #9334
Opened 2022-06-28 16:01 UTC by aaomidi

Per the RFC: https://datatracker.ietf.org/doc/html/rfc2986#section-4

Version 3 CSRs, as far as I can tell, are not a thing (yet).

Relevant code in Go, for example: https://cs.opensource.google/go/go/+/refs/tags/go1.18.3:src/crypto/x509/x509.go;l=1979

2022-06-28 17:53 UTC, aarongable commented
It's worth noting that the [documentation of the `.set_version()` method being called here](https://www.pyopenssl.org/en/stable/api/crypto.html#OpenSSL.crypto.X509Req.set_version) is itself wrong: it references [RFC 2459 Section 4.1.2.1](https://datatracker.ietf.org/doc/html/rfc2459#section-4.1.2.1) (which specifies the Version field for _Certificates_), when it should instead reference [RFC 2986 Section 4.1](https://datatracker.ietf.org/doc/html/rfc2986#section-4) (which specifies the Version field for CSRs). Consider also filing a bug/PR with [pyopenssl](https://github.com/pyca/pyopenssl) to update [that documentation](https://github.com/pyca/pyopenssl/blob/bd023272a93f600b0d7b666e15c01843ddb2f6d8/src/OpenSSL/crypto.py#L975-L994).

2022-06-28 17:56 UTC, aaomidi commented
@Zenexer volunteered to add a unit test to this PR. So marking it as draft until then.

2022-06-28 17:58 UTC, aaomidi commented
Thank you @aarongable for finding that. I'll see if I can make a PR, or at the very least make an issue.

2022-06-28 21:47 UTC, alexzorin requested changes
Thanks.

Looking at https://github.com/certbot/certbot/issues/2528, I think perhaps that the value `2` was mistakenly chosen [based on `TBSCertificate.version`](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1.2.1) rather than `CertificationRequestInfo.version`.

Could you please add a changelog entry for this? LGTM otherwise.

2022-06-29 04:24 UTC, alexzorin approved these changes
Thanks again.

2022-06-29 04:24 UTC, merged

2022-06-29 14:08 UTC, aaomidi commented
@alexzorin Any chance for cutting a release to get this PR out?

2022-06-30 02:18 UTC, alexzorin commented
This will be included in the monthly release next week.