Update Azure Docker docs
certbot/certbot pull request #9363
Opened 2022-07-22 18:23 UTC by bmw

This just updates this comment in response to switching to an access token to authenticate with Docker Hub.

2022-07-26 23:23 UTC, ohemorange requested changes
Found a few double spaces, but more importantly, do we think they're going to continue allowing PATs to bypass 2fa? I would have thought so, but the error that didn't seem to matter does give me some pause.

2022-07-26 23:23 UTC, ohemorange commented on .azure-pipelines/templates/stages/deploy-stage.yml
> +              # given to containerRegistry below.  The authentication used when
```suggestion
              # given to containerRegistry below. The authentication used when
```

2022-07-26 23:23 UTC, ohemorange commented on .azure-pipelines/templates/stages/deploy-stage.yml
> +              # account.  The access token can be deleted on Docker Hub if
```suggestion
              # account. The access token can be deleted on Docker Hub if
```

2022-07-28 15:23 UTC, bmw commented
> Found a few double spaces

I think the default vim config does this when line wrapping and I've never bothered to change it. Maybe I should.

> do we think they're going to continue allowing PATs to bypass 2fa? I would have thought so, but the error that didn't seem to matter does give me some pause.

I think so! https://docs.docker.com/docker-hub/access-tokens/ says:

> If you have [two-factor authentication (2FA)](https://docs.docker.com/docker-hub/2fa/) enabled on your account, you must create at least one personal access token. Otherwise, you will be unable to log in to your account from the Docker CLI.

I suspect I got the verification error I did because the Azure Pipelines site is trying to verify the PAT using a web interface which Docker Hub doesn't like.

2022-07-28 20:28 UTC, ohemorange approved these changes
That sounds safe enough re: PATs, lgtm!

2022-07-28 20:28 UTC, merged