deprecate more attributes in acme
certbot/certbot pull request #9369
Opened 2022-07-29 04:29 UTC by alexzorin

For #9365.

2022-07-29 18:47 UTC, bmw commented
To warn about `acme.messages.Authorization.combinations`, could we do something like this:
```
diff --git a/acme/acme/messages.py b/acme/acme/messages.py
index 9b9ef5de2..44ae8fbf6 100644
--- a/acme/acme/messages.py
+++ b/acme/acme/messages.py
@@ -603,6 +603,12 @@ class Authorization(ResourceBody):
                      for combo in self.combinations)  # pylint: disable=not-an-iterable
 
 
+    def __getattribute__(self, name):
+        if name == 'challenges':
+            # warn here
+        return super().__getattribute__(name)
+
+
 @Directory.register
 class NewAuthorization(ResourceMixin, Authorization):
     """New authorization."""
```
I believe this warns on reads and not writes.

The only downside I've seen so far is it warns on ANY read including those in the josepy code when doing things like hashing the object or serializing it to be sent the ACME server. Is this something you'd also like to avoid? If so, we may be able to do something by redefining the problematic josepy functions on `acme.messages.Authorization` in a way that [suppresses warnings](https://docs.python.org/3/library/warnings.html#temporarily-suppressing-warnings) and then just calls the original josepy function. Another option might be hiding the `challenges` field behind a new name and then writing something like a `challenge` property that raises a warning and returns the renamed field.

For `acme.messages.Authorization.resolved_combinations`, can we warn in the body of the function that defines the property? I think we could suppress the warning from `challenges` using the approach I linked above if we wanted.

2022-08-23 07:15 UTC, alexzorin commented
Thank you!!!

Turns out my initial confusion (where I had tried `__getattribute__` previously) had to do with my `python -d` REPL not including `DeprecationWarning` in its default filters. I thought `josepy` was preventing the warnings from being triggered by some magic but it was much simpler than that. Sorry, could have avoid bothering you in this case.

On the bright side, I really like the idea of renaming the field and warning on the property instead. You were right that `__getattribute__` is very noisy with `josepy`. I've gone with this idea.

2022-08-30 13:05 UTC, bmw requested changes
Other than some very minor tweaks, this LGTM!

In attempt to be helpful, I fixed up merge conflicts over three commits containing at least one typo... Feel free to do something else, but I think I can just clean this up when we squash this PR.

2022-08-30 21:32 UTC, bmw approved these changes

2022-08-30 21:41 UTC, merged