Create Weekly Notification Message for Certbot Team
certbot/certbot pull request #9600
Opened 2023-02-28 20:41 UTC by zoracon

Composes Mattermost message to team channel.

- Scheduled job that is sent once a week with dynamically set date range of past 7 days.

2023-03-01 00:39 UTC, wgreenberg commented on .github/workflows/notify_weekly.yaml
> +    - cron: "0 1 * * 4"
do we want this at 1am? if we want 1pm, it should be `0 13 * * 4`

2023-03-01 01:03 UTC, wgreenberg requested changes
one comment + one question!

2023-03-01 01:29 UTC, zoracon commented on .github/workflows/notify_weekly.yaml
> +        UPDATED_URL="https://github.com/pulls?q=updated%3A%3E${DATE}+org%3Acertbot+"
Don't think so. I just copy & pasted the query link. I will adjust.

2023-03-01 01:30 UTC, zoracon commented on .github/workflows/notify_weekly.yaml
> +    - cron: "0 1 * * 4"
I will adjust and also put `13:00` in the comment

2023-03-01 01:38 UTC, zoracon commented on .github/workflows/notify_weekly.yaml
> +    - cron: "0 1 * * 4"
```suggestion
    - cron: "0 13 * * 4"
```

2023-03-01 01:38 UTC, zoracon commented on .github/workflows/notify_weekly.yaml
> +    # Every week on Thursday @ 1:00
```suggestion
    # Every week on Thursday @ 13:00
```

2023-03-01 01:39 UTC, zoracon commented on .github/workflows/notify_weekly.yaml
> +        UPDATED_URL="https://github.com/pulls?q=updated%3A%3E${DATE}+org%3Acertbot+"
```suggestion
        MERGED_URL="https://github.com/pulls?q=merged%3A%3E${DATE}+org%3Acertbot"
        UPDATED_URL="https://github.com/pulls?q=updated%3A%3E${DATE}+org%3Acertbot"
```

2023-03-06 20:16 UTC, wgreenberg approved these changes

2023-03-06 20:18 UTC, merged