Do not call deprecated datetime.utcnow() and datetime.utcfromtimestamp()
certbot/certbot pull request #9735
Opened 2023-07-15 23:23 UTC by ellert

With Python 3.12:

~~~
# python3
Python 3.12.0b4 (main, Jul 12 2023, 00:00:00) [GCC 13.1.1 20230614 (Red Hat 13.1.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.utcnow()
<stdin>:1: DeprecationWarning: datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
datetime.datetime(2023, 7, 15, 23, 20, 12, 672120)
>>> datetime.datetime.utcfromtimestamp(0)
<stdin>:1: DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.fromtimestamp(timestamp, datetime.UTC).
datetime.datetime(1970, 1, 1, 0, 0)
~~~

## Pull Request Checklist

- [ ] The Certbot team has recently expressed interest in reviewing a PR for this. If not, this PR may be closed due our limited resources and need to prioritize how we spend them.
- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [ ] Add or update any documentation as needed to support the changes in this PR.
- [ ] Include your name in `AUTHORS.md` if you like.

2023-07-17 20:02 UTC, ohemorange requested changes

2023-07-17 23:28 UTC, ellert commented on acme/acme/_internal/tests/fields_test.py
> +        self.decoded = datetime.datetime(2015, 3, 27, tzinfo=pytz.UTC)
Yes, they are the same. But using different ones in different parts of the code is confusing, and there were only two "pytz.utc" to change to make it consistent. I do not insist on this change. It just wanted to help others reading the code not having to be as confused as I was.

2023-07-17 23:29 UTC, ellert commented on acme/acme/fields.py
> +    (e.g. ``datetime.datetime.now(pytz.UTC)``).
same as above

2023-07-17 23:33 UTC, ellert commented on certbot/certbot/_internal/cert_manager.py
> +    now = datetime.datetime.now(pytz.UTC)
pytz.UTC.fromutc() is a no-op on a datetime object with tzinfo=pytz.UTC, so removing it does not change anything.

>>> now = datetime.datetime.now(pytz.UTC)
>>> now
datetime.datetime(2023, 7, 17, 23, 9, 16, 174051, tzinfo=<UTC>)
>>> pytz.UTC.fromutc(now)
datetime.datetime(2023, 7, 17, 23, 9, 16, 174051, tzinfo=<UTC>)

2023-07-17 23:34 UTC, ellert commented on certbot/certbot/_internal/tests/cert_manager_test.py
> +        expiry = datetime.datetime.now(pytz.UTC);
Agree.

2023-07-17 23:36 UTC, ellert commented on certbot/certbot/_internal/tests/ocsp_test.py
> +        next_update=datetime.now(pytz.UTC).replace(tzinfo=None) + timedelta(days=1),
This is a mock.Mock() object mocking an OCSP response object. The OCSP object it is mocking has the this and next update times in datetime objects in UTC, but with tzinfo=None. The original code was using datetime.now(), which actually wasn't quite right. This has the right format (i.e. tzinfo=None), but returns local time, not UTC.

pytz.UTC.localize() does the exact opposite of what is needed here, i.e. it adds tzinfo to a datetime object where it is None:

>>> time = datetime.datetime(2023, 7, 18, 12, 0)
>>> time
datetime.datetime(2023, 7, 18, 12, 0)
>>> pytz.UTC.localize(time)
datetime.datetime(2023, 7, 18, 12, 0, tzinfo=<UTC>)

We want to remove the tzinfo, not add:

>>> now = datetime.datetime.now(pytz.UTC)
>>> now
datetime.datetime(2023, 7, 17, 23, 9, 16, 174051, tzinfo=<UTC>)
>>> now.replace(tzinfo=None)
datetime.datetime(2023, 7, 17, 23, 9, 16, 174051)

datetime.UTC.fromutc() does not do the right thing either. It is a no-op when the tzinfo already is pytz.UTC:

>>> now = datetime.datetime.now(pytz.UTC)
>>> now
datetime.datetime(2023, 7, 17, 23, 9, 16, 174051, tzinfo=<UTC>)
>>> pytz.UTC.fromutc(now)
datetime.datetime(2023, 7, 17, 23, 9, 16, 174051, tzinfo=<UTC>)

2023-07-18 15:30 UTC, ellert commented on acme/acme/_internal/tests/fields_test.py
> +        self.decoded = datetime.datetime(2015, 3, 27, tzinfo=pytz.UTC)
I have moved these two changes to a separate commit.

2023-07-18 22:44 UTC, ohemorange approved these changes
LGTM, thank you!

2023-07-18 22:44 UTC, ohemorange commented on certbot/certbot/_internal/cert_manager.py
> +    now = datetime.datetime.now(pytz.UTC)
I see, the point of this previously was to add the tzinfo into the naive object.

2023-07-18 22:44 UTC, ohemorange commented on acme/acme/_internal/tests/fields_test.py
> +        self.decoded = datetime.datetime(2015, 3, 27, tzinfo=pytz.UTC)
That's helpful feedback, seems worth it for this purpose.

2023-07-18 22:44 UTC, ohemorange commented on certbot/certbot/_internal/tests/ocsp_test.py
> +        next_update=datetime.now(pytz.UTC).replace(tzinfo=None) + timedelta(days=1),
Ah, yes I see now. Nice catch!

2023-07-18 22:44 UTC, merged