Pkg resources to importlib resources
certbot/certbot pull request #9748
Opened 2023-08-15 19:53 UTC by adferrand

First part to treat https://github.com/certbot/certbot/issues/9606

In this PR, usages of `pkg_resources` that are now covered by `importlib.resources` are migrated to `importlib`. Backport of `importlib_resources` is added to the dependencies to ensure that the code on older version of Python (3.7 & 3.8).

The migration essentially follows https://importlib-resources.readthedocs.io/en/latest/migration.html. The code using `pkg_resources.parse_version` are either removed or replaced by `certbot.util.parse_loose_version`.

2023-08-29 20:02 UTC, wgreenberg requested changes
looks good! just a few suggestions, but feel free to ignore them.

2023-08-29 20:02 UTC, wgreenberg commented on certbot/certbot/_internal/constants.py
> +_SSL_DHPARAMS_SRC_REF = importlib_resources.files("certbot") / "ssl-dhparams.pem"
ditto re: placing this in a function

2023-08-29 21:13 UTC, adferrand commented on certbot-apache/certbot_apache/_internal/constants.py
> +    importlib_resources.as_file(_AUGEAS_LENS_DIR_REF)))
Good idea, I did that!

2023-08-29 21:14 UTC, adferrand commented on certbot/certbot/_internal/constants.py
> +_SSL_DHPARAMS_SRC_REF = importlib_resources.files("certbot") / "ssl-dhparams.pem"
Same.

2023-09-07 18:38 UTC, wgreenberg approved these changes

2023-09-07 18:38 UTC, wgreenberg commented
LGTM, thanks @adferrand!

2023-09-07 18:38 UTC, merged