Print error details when an IssuanceError is thrown
certbot/certbot pull request #9804
Opened 2023-10-16 15:44 UTC by TheEnbyperor

When a CA fails to issue a certificate after finalisation Certbot currently prints the following unhelpful message:

```
An unexpected error occurred:
acme.errors.IssuanceError
```

This PR makes Certbot print the ACME error object from the order, as such

```
An unexpected error occurred:
CAA error :: Invalid CAA: CAA prohibits issuance
```

## Pull Request Checklist

- [ ] The Certbot team has recently expressed interest in reviewing a PR for this. If not, this PR may be closed due our limited resources and need to prioritize how we spend them.
- [x] If the change being made is to a [distributed component](https://certbot.eff.org/docs/contributing.html#code-components-and-layout), edit the `master` section of `certbot/CHANGELOG.md` to include a description of the change being made.
- [x] Add or update any documentation as needed to support the changes in this PR.
- [x] Include your name in `AUTHORS.md` if you like.

2025-02-14 23:01 UTC, ohemorange requested changes
Found this in our backlog and appreciate the change; would you mind moving up the changelog entry to the current section?

2025-06-11 21:27 UTC, ohemorange commented
Closing in favor of https://github.com/certbot/certbot/pull/10331

2025-06-11 21:42 UTC, TheEnbyperor commented
Oops, I somehow missed your comment of the 15th of Feb. I don't seem to be able to update this PR any more myself now.

2025-06-11 21:54 UTC, ohemorange commented
Reopened the PR. If you want to handle the merge and move up the changelog entry as I did, feel free. Otherwise it'll just get handled in the other PR. Either way your authorship of the actual fix will be preserved.

2025-06-11 22:00 UTC, TheEnbyperor commented
Should all be correct now.

2025-06-11 22:15 UTC, merged