Add support for Alpine Linux
certbot/certbot pull request #9834
Opened 2023-11-02 12:34 UTC by fcolista

Hi, I'm the certbot maintainer for Alpine Linux (https://www.alpinelinux.org).
We are using this patch downstream: https://git.alpinelinux.org/aports/commit/?id=85f48c053ea3bd0d4c2cf4f34ad17ecef0b06849

Perhaps would be nice if you implement directly upstream :)
Thank you for considering.

2023-11-12 13:09 UTC, adferrand requested changes
That totally makes sense. Could you add also an entry in the changelog?

2023-11-22 09:41 UTC, fcolista commented
@adferrand  thanks for your suggestion.
Done as you requested.
Is there something else needed from my side to get this merged?
Thanks!

2023-11-22 10:13 UTC, adferrand commented
Sorry @fcolista, but I do not see any change on the changelog in your PR. Have you commited it ?

2023-11-22 10:21 UTC, fcolista commented
Apologize. I did it but forgot to push :D
Just pushed.

.: Francesco Colista








Il giorno mer 22 nov 2023 alle ore 11:13 Adrien Ferrand <
***@***.***> ha scritto:

> Sorry @fcolista <https://github.com/fcolista>, but I do not see any
> change on the changelog in your PR. Have you commited it ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/certbot/certbot/pull/9834#issuecomment-1822473642>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA6P6354PHNIC5GBOB7VXPTYFXF3XAVCNFSM6AAAAAA62Z6J2WVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMRSGQ3TGNRUGI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-11-22 12:53 UTC, adferrand approved these changes
All good to me! Thanks :)

2023-11-22 12:53 UTC, merged